name: Generate snake game

on:
  schedule:
    - cron: "0 0 * * *"  # هر روز در نیمه‌شب اجرا می‌شه
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aliprog1241  # username خودت رو بذار
          svg_out_path: dist/snake.svg
          gif_out_path: dist/snake.gif
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
            dist/pacman-contribution-graph.gif

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
